name: "OpenCode"
description: "AI coding assistant"
version: "1.3.29"
slug: "opencode"
startup: services
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw
  - share:rw
ingress: false
panel_icon: "mdi:robot-code"
panel_title: "OpenCode"
ports:
  4096/tcp: 4096
options:
  password: "change_me"
schema:
  password: "str"
