name: "OpenCode"
description: "High-performance AI server (Ingress Secured)"
version: "1.3.6"
slug: "opencode"
startup: services
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw
  - share:rw
ingress: true
ingress_port: 8099
panel_icon: "mdi:robot-code"
panel_title: "OpenCode"
options:
  password: "change_me_immediately"
  port: 4096
schema:
  password: "str"
  port: "int"
